from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Seguros.views.home', name='home'),
    # url(r'^Seguros/', include('Seguros.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    # URL del proyecto
    url(r'^$', 'ConexosAgropecuarios.views.inicio'),
    url(r'^ActaSiniestroGuardar/$', 'Siniestro.views.guardar_acta_siniestro'),
    url(r'^ActaVerificacion/(?P<id_Solicitud>\d+)$', 'Solicitud.views.actaVerificacion'),
    url(r'^ActaSiniestro/(?P<id_inspeccion>\d+)$', 'Siniestro.views.acta_siniestro'),    
    url(r'^AvisoSiniestroEditar/(?P<id_aviso_siniestro>\d+)$', 'Siniestro.views.avisoSiniestroEditar'),    
    url(r'^AvisoSiniestroNuevo/$', 'Siniestro.views.avisoSiniestroNuevo'),
    url(r'^CartaConstancia/(?P<id_Constancia>\d+)$', 'Cobranza.views.cartaConstancia'),
    url(r'^CobroEndosoCancelacion/(?P<id_endoso>\d+)$', 'Cobranza.views.cobroEndosoCancelacion'),
    url(r'^CartaNoSiniestro/(?P<id_Constancia>\d+)$', 'Cobranza.views.cartaNoSiniestro'),
    url(r'^SettingsUser/$', 'Login.views.settingsUser'),
    url(r'^Constancia/(?P<id_Solicitud>\d+)$', 'Constancias.views.constancia'),
    url(r'^Cotizadores/$', 'Cotizador.views.cotizadores'),
    url(r'^Cotizador/$', 'Cotizador.views.cotizador'),
    url(r'^CotizadorEditar/(?P<id_cotizador>\d+)$', 'Cotizador.views.cotizadorEditar'),
    url(r'^DatosFondo/$', 'ConexosAgropecuarios.views.datosFondo'),
    url(r'^DeclaracionEndoso/(?P<id_endoso>\d+)$', 'Endoso.views.declaracionEndoso'),
    url(r'^DeclaracionEndoso/$', 'Endoso.views.declaracion_Endoso_Sin_Id'),
    url(r'^DeclaracionEndosoConstancia/(?P<id_constancia>\d+)$', 'Endoso.views.declaracionEndoso_Id_Constancia'),
    url(r'^DeclaracionEndosoImpresion/(?P<id_declaracion>\d+)$', 'Endoso.views.declaracion_Endoso_Impresion'),
    url(r'^DeclaracionTransporte/(?P<id_declaracion_transporte>\d+)$', 'Endoso.views.declaracionEndoso_id_declaracion_transporte'),  
    url(r'^DeclaracionTransporteConstancia/(?P<id_constancia>\d+)$', 'Endoso.views.declaracionTransporte_Id_Constancia'), 
    url(r'^DeclaracionTransporte/$', 'Endoso.views.declaracionTransporte'),
    url(r'^DeclaracionTransporteImpresion/(?P<id_declaracion>\d+)$', 'Endoso.views.declaracion_Transporte_Impresion'),
    url(r'^', include('Siniestro.urls', namespace = 'Siniestro', app_name='Siniestro')),
    url(r'^EndosoAumento/(?P<pk>\d+)$', 'Endoso.views.endoso_aumento_detail',name='endoso_aumento_detail'),
    url(r'^EndosoADImpresion/(?P<id_ControlEndoso>\d+)$', 'Endoso.views.EndosoAumentoDisminucionPdf'),
    url(r'^EndosoCancelacion/(?P<id_constancia>\d+)$', 'Endoso.views.endoso_cancelacion'),
    url(r'^EndosoDeclaracion/(?P<id_declaracion>\d+)$', 'Endoso.views.endosoDeclaracion'),
    url(r'^EndosoDeclaracionImpresion/(?P<id_declaracion>\d+)$', 'Endoso.views.endoso_Declaracion_Impresion'),
    url(r'^EndosoDisminucion/(?P<pk>\d+)$', 'Endoso.views.endoso_disminucion_detail',name='endoso_disminucion_detail'),    
    url(r'^EndosoTransporte/(?P<id_declaracion>\d+)$', 'Endoso.views.endosoTransporte'), 
    url(r'^EndosoTransporteImpresion/(?P<id_declaracion>\d+)$', 'Endoso.views.endoso_Transporte_Impresion'),  
    url(r'^HistorialDeclaracionEndosoConstancia/$', 'Endoso.views.historial_declaracion_endoso'),        
    url(r'^HistorialDeclaracionTransporteConstancia/$', 'Endoso.views.historial_declaracion_transporte'),
    url(r'^InspeccionEditar/(?P<id_inspeccion>\d+)$', 'Siniestro.views.inpeccion_editor'),    
    url(r'^InspeccionNueva/$', 'Siniestro.views.inpeccion_nueva'),      
    url(r'^ListadoActasVerificacion/$', 'Solicitud.views.listaActasVerificacion'),
    url(r'^ListadoActasVerificacionRechazadas/$', 'Solicitud.views.listaActasVerificacionRechazadas'),
    url(r'^ListadoAumentoEndoso/$', 'Endoso.views.listadoAumentoEndoso'),
    url(r'^ListadoAvisoSiniestro/$', 'Siniestro.views.listaAvisoSiniestro'),    
    url(r'^ListadoCobroConstancias/$', 'Cobranza.views.listaCobroConstancias'),
    url(r'^ListadoCobroEndosos/$', 'Cobranza.views.listaCobroEndosos'),
    url(r'^ListadoCobroEndosoCancelacion/$', 'Cobranza.views.listaCobroEndosoCancelacionADeclaracion'),    
    url(r'^ListadoConstancias/$', 'Constancias.views.listaConstancias'),
    url(r'^ListadoDeclaracionEndoso/$', 'Endoso.views.listadoDeclaracionEndoso'),
    url(r'^ListadoDeclaracionTransporte/$', 'Endoso.views.listadoDeclaracionTransporte'),
    url(r'^ListadoDisminucionEndoso/$', 'Endoso.views.listadoDisminucionEndoso'), 
    url(r'^ListadoCancelacionEndoso/$', 'Endoso.views.listado_endosos_cancelacion'),
    url(r'^ListadoInspecciones/$', 'Siniestro.views.listadoInspecciones'),
    url(r'^ListadoPagoEndosoCancelacionAnual/$', 'Cobranza.views.listaPagoEndosoCancelacionAnual'),
    url(r'^ListadoPagoPrimaDeposito/$', 'Cobranza.views.listaPagoPrimaDeposito'),
    url(r'^ListadoRehabilitarConstanciasCanceladas/$','Cobranza.views.listaRehabilitarConstanciasCanceladas'),
    url(r'^ListadoSolicitudEndoso/$', 'Endoso.views.listadoSolicitudEndoso'),
    url(r'^Login/$', 'Login.views.login'),
    url(r'^Logout/$', 'Login.views.logout'),
    url(r'^ListadoPagoEndoso/$', 'Cobranza.views.listaPagoEndoso'),
    url(r'^PagoConstancia/(?P<pk>\d+)$', 'Cobranza.views.pago_constancia_detail',name='pago_constancia_detail'),    
    url(r'^PagoEndoso/(?P<id_controlendoso>\d+)$', 'Cobranza.views.pagoEndoso'),
    url(r'^PagoEndosoTransporteDeclaracion/(?P<id_declaracion>\d+)/(?P<tipo_declaracion>\w+)$', 'Cobranza.views.cobroEndosoTransporteDeclaracion'),
    url(r'^PagoEndosoCancelacionAnual/(?P<id_endoso>\d+)$', 'Cobranza.views.pagoEndosoCancelacionAnual'),    
    url(r'^PagoPrimaDeposito/(?P<id_constancia>\d+)$', 'Cobranza.views.pagoPrimaDeposito'),
    url(r'^PersonaFisica/$', 'ConexosAgropecuarios.views.personaFisica'),
    url(r'^PersonaMoral/$', 'ConexosAgropecuarios.views.personaMoral'),
    url(r'^Programas/$', 'Programas.views.programas'),
    url(r'^Programa/$', 'Programas.views.programa'),
    url(r'^Programa/(?P<id_programa>\d+)$', 'Programas.views.programa'),
    url(r'^Solicitudes/$', 'Solicitud.views.solicitudes'),
    url(r'^Solicitud/$', 'Solicitud.views.solicitud'),
    url(r'^SolicitudEndoso/(?P<pk>\d+)$', 'Endoso.views.solicitud_endoso_detail',name='solicitud_endoso_detail'),
    url(r'^SolicitudEndosoImpresion/(?P<id_SolicitudEndoso>\d+)$', 'Endoso.views.SolicitudEndosoImpresion'),
    url(r'^ReciboPagoPrimaDeposito/(?P<id_pago>\d+)$', 'Cobranza.views.reciboPagoPrimaDeposito'),
    url(r'^RelacionAnexaActaVerificacion/(?P<id_Solicitud>\d+)$', 'Solicitud.views.relacionAnexaActaVerificacion'),
    url(r'^RelacionAnexaSolicitudAseguramiento/(?P<id_Solicitud>\d+)$', 'Solicitud.views.relacionAnexaSolicitudAseguramiento'),
    url(r'^ReporteActaSiniestro/(?P<id_inspeccion>\d+)$', 'Siniestro.views.reporte_acta_siniestro'),    
    url(r'^ReporteActaVerificacion/(?P<id_Solicitud>\d+)$', 'Solicitud.views.reporteActaVerificacion'),
    url(r'^ReporteAvisoSiniestro/(?P<id_aviso>\d+)$', 'Siniestro.views.reporte_aviso_siniestro'),        
    #url(r'^ReporteBordereaux/$', 'Reporteador.views.reporteBordereaux'),
    url(r'^', include('Reporteador.urls', namespace = 'Reporteador', app_name='Reporteador')),
    url(r'^ReporteCobroEndosoCancelacion/(?P<id_cobro>\d+)$', 'Cobranza.views.reciboCobroEndosoCancelacion'),
    url(r'^ReporteConstancia/(?P<id_Constancia>\d+)$', 'Constancias.views.reporteConstancia'),
    url(r'^ReporteCotizador/$', 'Cotizador.views.reporteCotizador'),
    url(r'^ReporteEndosoCancelacion/(?P<id_endoso>\d+)$', 'Endoso.views.reporte_endoso_cancelacion'),
    url(r'^ReportePagoEndoso/(?P<id_declaracion>\d+)/(?P<tipo_endoso>\w+)$', 'Cobranza.views.reporteReciboPagoEndoso'), 
    url(r'^ReportePagoEndosoAumento/(?P<id_pagoendoso>\d+)$', 'Cobranza.views.reporteReciboPagoEndosoAumento'),
    url(r'^ReportePagoEndosoCancelacion/(?P<id_pago>\d+)$', 'Cobranza.views.reciboPagoEndosoCancelacion'),
    url(r'^ReportePrograma/$', 'Programas.views.reportePrograma'),
    url(r'^ReporteRelacionAnexa/(?P<id_Solicitud>\d+)$', 'Solicitud.views.reporteRelacionAnexaSolicitudAseguramiento'),
    url(r'^ReporteRelacionAnexaActaVerificacion/(?P<id_Solicitud>\d+)$', 'Solicitud.views.reporteRelacionAnexaActaVerificacion'),
    url(r'^ReporteSolicitud/$', 'Solicitud.views.reporteSolicitud'),
    url(r'^ObtenerBienesActaSiniestro/$', 'Siniestro.views.obtener_bienes_acta_siniestro'),
)

urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT,}),                        
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.STATIC_ROOT,}), #servirlos en produccion
)

handler404 = "ConexosAgropecuarios.views.handler404"